# Site settings
title:          ICON Club
email:          icon.acaclub@it.tdt.edu.vn
description:    "Blog chia sẻ của ICON Club"
baseurl:        "/blog"
url:            "https://iconclub.github.io"

# Author
author:
  name:         ICON CLub
  url:          https://iconclub.github.io
  email:        icon.acaclub@it.tdt.edu.vn

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, icon.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale